"""empty message

Revision ID: 979ccbfb4d37
Revises: 
Create Date: 2023-09-28 10:03:16.686714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '979ccbfb4d37'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edtech',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('course_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('edtech')
    # ### end Alembic commands ###
